name: Prueba DevOps

on:
  push:
    branches: [ "main" ]

jobs:
  prueba:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Mostrar mensaje
        run: echo "¡La automatización de DevOps funciona correctamente!"

      - name: Verificar archivos
        run: ls -la
